pengiriman/urls.py
from django.urls import path

from . import views

app_name = 'pengiriman'

urlpatterns = [
    path('kendaraan/', views.kendaraan, name='kendaraan'),
    path('kendaraan/add/', views.add_kendaraan, name='add_kendaraan'),
    path('kendaraan/update/<str:nomor_kendaraan>', views.update_kendaraan, name='update_kendaraan'),
    path('kendaraan/delete/<str:nomor_kendaraan>', views.delete_kendaraan, name='delete_kendaraan'),
    path('batch/', views.batch, name='batch'),
    path('batch/add/<str:nomor_transaksi>', views.add_batch, name='add_batch'),
    path('batch/detail/<int:no_transaksi>', views.detail_batch, name='detail_batch'),
    path('lokasi/', views.lokasi, name='lokasi'),
    path('lokasi/add/', views.add_lokasi, name='add_lokasi'),
    path('lokasi/update/<str:lokasi_id>', views.update_lokasi, name='update_lokasi'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pengguna.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('trigger3/',include('trigger3.urls')),
    path('trigger6/', include ('trigger6.urls')),
    path('faskes/', include('faskes.urls')),
    path('warehouse/', include('warehouse.urls'))
]

trigger6/urls.py
from django.urls import path

from . import views

app_name = 'trigger6'

urlpatterns = [
    path('WarehouseStockCreate', views.WarehouseStockCreate, name = 'WarehouseStockCreate'),
    path('WarehouseStockRead', views.WarehouseStockRead, name = 'WarehouseStockRead'),
    path('WarehouseStockUpdate/<str:warehouse>/<str:item>', views.WarehouseStockUpdate, name = 'WarehouseStockUpdate'),
    path('WarehouseStockReadFaskes', views.WarehouseStockReadFaskes, name = 'WarehouseStockReadFaskes'),

    path('RiwayatStatusBatchCreate', views.RiwayatStatusBatchCreate, name = 'RiwayatStatusBatchCreate'),
    path('RiwayatStatusBatchRead', views.RiwayatStatusBatchRead, name = 'RiwayatStatusBatchRead')
]

pengiriman/models.py
from django.db import models

# Create your models here.

pengiriman/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError, InternalError, connection
from django.contrib import messages

import random, string

# Create your views here.

def kendaraan(request):
    with connection.cursor() as cursor:

        cursor.execute(f"""
            SELECT * FROM kendaraan
        """)

        context = {"kendaraans" : cursor.fetchall()}

    return render(request, "pengiriman/kendaraan.html", context)

def add_kendaraan(request):
    if request.session["role"] == "admin":
        if request.method == "POST":

            try:
                with connection.cursor() as cursor:

                    cursor.execute(f"""
                        INSERT INTO kendaraan VALUES 
                        ('{request.POST['nomor']}',
                        '{request.POST['nama']}',
                        '{request.POST['jenis']}',
                        '{request.POST['berat']}')
                    """)

                    return redirect("pengiriman:kendaraan")
            
            except IntegrityError:
                messages.add_message(request, messages.WARNING, f"Kendaraan dengan nomor {request.POST['nomor']} sudah terdaftar")

        return render(request, "pengiriman/kendaraan_add.html")

    else:
        return redirect("pengguna:wrong_role")

def update_kendaraan(request, nomor_kendaraan):
    if request.session["role"] == "admin":
        if request.method == "POST":
            with connection.cursor() as cursor:

                cursor.execute(f"""
                    UPDATE kendaraan SET
                    nomor='{request.POST['nomor']}',
                    nama='{request.POST['nama']}',
                    jenis_kendaraan='{request.POST['jenis']}',
                    berat_maksimum='{request.POST['berat']}'
                    WHERE nomor='{nomor_kendaraan}'
                """)

                return redirect("pengiriman:kendaraan")
        
        else:
            with connection.cursor() as cursor:

                cursor.execute(f"""
                    SELECT * FROM kendaraan
                    WHERE nomor='{nomor_kendaraan}'
                """)

                context = {"kendaraan" : cursor.fetchall()[0]}

            return render(request, "pengiriman/kendaraan_update.html", context)
    
    else:
        return redirect("pengguna:wrong_role")

def delete_kendaraan(request, nomor_kendaraan):
    if request.session["role"] == "admin":
        with connection.cursor() as cursor:

            cursor.execute(f"""
                DELETE FROM kendaraan
                WHERE nomor='{nomor_kendaraan}'
            """)

            return redirect("pengiriman:kendaraan")

    else:
        return redirect("pengguna:wrong_role")

def batch(request):

    username = request.session["username"]
    role = request.session["role"]

    context = {'role': role}

    if role == "admin":
        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT psd.no_transaksi_sumber_daya, psd.username_petugas_faskes, f.kode_faskes_nasional, tsd.total_berat, rsp.status_permohonan, sb.status_batch
                FROM permohonan_sumber_daya_faskes AS psd
                NATURAL JOIN (
                    SELECT DISTINCT ON (nomor_permohonan)
                    nomor_permohonan AS no_transaksi_sumber_daya, kode_status_permohonan AS status_permohonan
                    FROM riwayat_status_permohonan
                    ORDER BY nomor_permohonan, tanggal DESC
                    ) AS rsp
                INNER JOIN transaksi_sumber_daya AS tsd ON tsd.nomor=psd.no_transaksi_sumber_daya
                INNER JOIN faskes AS f ON f.username_petugas=psd.username_petugas_faskes
                LEFT JOIN (
                    SELECT nomor_transaksi_sumber_daya, sp.status_batch
                    FROM batch_pengiriman
                    NATURAL JOIN (
                        SELECT DISTINCT ON (kode_batch)
                        kode_batch AS kode, kode_status_batch_pengiriman AS status_batch
                        FROM riwayat_status_pengiriman
                        ORDER BY kode_batch, tanggal DESC
                        ) AS sp
                    ) AS sb ON sb.nomor_transaksi_sumber_daya=psd.no_transaksi_sumber_daya
                ORDER BY psd.no_transaksi_sumber_daya;
            """)

            context['permohonans'] = cursor.fetchall()

        return render(request, "pengiriman/batch.html", context)

    elif role == "faskes":
        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT psd.no_transaksi_sumber_daya, psd.username_petugas_faskes, f.kode_faskes_nasional, tsd.total_berat, rsp.status_permohonan, sb.status_batch
                FROM (SELECT * FROM permohonan_sumber_daya_faskes as psd where psd.username_petugas_faskes='{username}')AS psd
                NATURAL JOIN (
                    SELECT DISTINCT ON (nomor_permohonan)
                    nomor_permohonan AS no_transaksi_sumber_daya, kode_status_permohonan AS status_permohonan
                    FROM riwayat_status_permohonan
                    ORDER BY nomor_permohonan, tanggal DESC
                    ) AS rsp
                INNER JOIN transaksi_sumber_daya AS tsd ON tsd.nomor=psd.no_transaksi_sumber_daya
                INNER JOIN faskes AS f ON f.username_petugas=psd.username_petugas_faskes
                LEFT JOIN (
                    SELECT nomor_transaksi_sumber_daya, sp.status_batch
                    FROM batch_pengiriman
                    NATURAL JOIN (
                        SELECT DISTINCT ON (kode_batch)
                        kode_batch AS kode, kode_status_batch_pengiriman AS status_batch
                        FROM riwayat_status_pengiriman
                        ORDER BY kode_batch, tanggal DESC
                        ) AS sp
                    ) AS sb ON sb.nomor_transaksi_sumber_daya=psd.no_transaksi_sumber_daya
                ORDER BY psd.no_transaksi_sumber_daya;
            """)

            context['permohonans'] = cursor.fetchall()

        return render(request, "pengiriman/batch.html", context)

    elif role == "distribusi":
        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT psd.no_transaksi_sumber_daya, psd.username_petugas_faskes, f.kode_faskes_nasional, tsd.total_berat, rsp.status_permohonan, sb.status_batch
                FROM permohonan_sumber_daya_faskes AS psd
                NATURAL JOIN (
                    SELECT DISTINCT ON (nomor_permohonan)
                    nomor_permohonan AS no_transaksi_sumber_daya, kode_status_permohonan AS status_permohonan
                    FROM riwayat_status_permohonan
                    ORDER BY nomor_permohonan, tanggal DESC
                    ) AS rsp
                INNER JOIN transaksi_sumber_daya AS tsd ON tsd.nomor=psd.no_transaksi_sumber_daya
                INNER JOIN faskes AS f ON f.username_petugas=psd.username_petugas_faskes
                JOIN (
                    SELECT nomor_transaksi_sumber_daya, sp.status_batch
                    FROM (SELECT * from batch_pengiriman where username_petugas_distribusi='{username}') as batch_pengiriman
                    NATURAL JOIN (
                        SELECT DISTINCT ON (kode_batch)
                        kode_batch AS kode, kode_status_batch_pengiriman AS status_batch
                        FROM riwayat_status_pengiriman
                        ORDER BY kode_batch, tanggal DESC
                        ) AS sp
                    ) AS sb ON sb.nomor_transaksi_sumber_daya=psd.no_transaksi_sumber_daya
                ORDER BY psd.no_transaksi_sumber_daya;
            """)

            context['permohonans'] = cursor.fetchall()

        return render(request, "pengiriman/batch.html", context)

    else:
        return redirect("pengguna:wrong_role")

def add_batch(request, nomor_transaksi):
    if request.session["role"] == "admin":
        if request.method == "POST":

            with connection.cursor() as cursor:
                
                if request.POST['petugas'] != "none" and request.POST['kendaraan'] != "none":
                    if len(request.POST['kode']) == 5:
                        try:
                            # Generate tanda terima
                            tanda_terima = ''.join(random.choices(string.ascii_letters + string.digits, k=30))

                            cursor.execute(f"""
                                INSERT INTO batch_pengiriman(kode,username_satgas,username_petugas_distribusi,
                                tanda_terima,nomor_transaksi_sumber_daya,no_kendaraan) VALUES 
                                ('{request.POST['kode']}',
                                '{request.POST['admin']}',
                                '{request.POST['petugas']}',
                                '{tanda_terima}',
                                '{request.POST['nomor']}',
                                '{request.POST['kendaraan']}')
                            """)

                            messages.add_message(request, messages.SUCCESS, "Batch pengiriman berhasil ditambahkan")

                        except InternalError:
                            messages.add_message(request, messages.WARNING, "Batch pengiriman untuk permohonan sumber daya ini sudah cukup")

                        except:
                            messages.add_message(request, messages.WARNING, "Terjadi masalah saat menambahkan batch pengiriman")

                    else:
                        messages.add_message(request, messages.WARNING, "Jumlah batch pengiriman sudah melewati batas maksimal sistem")

                else:
                    messages.add_message(request, messages.WARNING, "Terdapat data yang belum diisi, silakan lengkapi data terlebih dahulu")

        with connection.cursor() as cursor:

            # Generate kode batch (mungkin bisa dikasih batasan)

pengiriman/templates/pengiriman/batch.html
{% extends 'pengguna/base.html' %}

{% block body %}

<table>
  <tr>
    <th>No. Transaksi</th>
    <th>Petugas Faskes</th>
    <th>Faskes</th>
    <th>Total Berat (kg)</th>
    <th>Status Permohonan</th>
    <th>Status Batch</th>
    <th>Action</th>
  </tr>

  {% for permohonan in permohonans %}

  <tr>
    <td>{{ permohonan.0 }}</td>
    <td>{{ permohonan.1 }}</td>
    <td>{{ permohonan.2 }}</td>
    <td>{{ permohonan.3 }}</td>
    <td>{{ permohonan.4 }}</td>
    <td>{{ permohonan.5 }}</td>
    <td>

      {% if role == "admin" %}
      {% if permohonan.5 == "PRO" or not permohonan.5 %}
      <form action="{% url 'pengiriman:add_batch' permohonan.0 %}">
        <input type="submit" value="Buat Batch" />
      </form>
      {% endif %}
      {% endif %}

      {% if permohonan.4 == "FIN" or permohonan.4 == "MAS" %}
      {% if permohonan.5 == "DLV" or permohonan.5 == "OTW" or permohonan.5 == "HLG" or permohonan.5 == "RET" %}
      <form action="{% url 'pengiriman:detail_batch' permohonan.0 %}">
        <input type="submit" value="Detail" />
      </form>
      {% endif %}
      {% endif %}

      {% if role == "admin" %}
      {% if permohonan.5 == "PRO" or permohonan.5 == "OTW" %}
        <a href="{% url 'trigger6:RiwayatStatusBatchCreate' %}"><button>Ubah Status</button></a>
      {% endif %}
      {% endif %}

      {% if role == "admin" or role == "distribusi" %}
      {% if permohonan.5 %}
        <a href="{% url 'trigger6:RiwayatStatusBatchRead' %}"><button>Riwayat Status</button></a>
      {% endif %}
      {% endif %}

    </td>
  </tr>

  {% endfor %}
</table>

{% endblock body %}

pengiriman/templates/pengiriman/batch_add.html
{% extends 'pengguna/base.html' %}

{% load static %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<form method="POST" action="{% url 'pengiriman:add_batch' nomor_transaksi %}">

    <label for="input-admin">Username Petugas Satgas:</label>
    <input id="input-admin" name="admin" type="text" value="{{ request.session.username }}" readonly>

    <br>

    <label for="input-nomor">Nomor Transaksi Sumber Daya:</label>
    <input id="input-nomor" name="nomor" type="text" value="{{ nomor_transaksi }}" readonly>

    <br>

    <br><h3>Buat Batch Pengiriman</h3><br>

    <label for="input-kode">Kode Batch:</label>
    <input id="input-kode" type="text" name="kode" value="{{ kode_batch }}" readonly>

    <br>

    <p id="form-kendaraan">Kendaraan: Belum Dipilih</p>
    <input id="input-kendaraan" name="kendaraan" type="hidden" value="none">
    <button type="button" data-toggle="modal" data-target=".pilih-kendaraan-modal">Pilih Kendaraan</button>

    <p id="form-petugas-distribusi">Petugas Distribusi: Belum Dipilih</p>
    <input id="input-petugas-distribusi" name="petugas" type="hidden" value="none">
    <button type="button" data-toggle="modal" data-target=".pilih-petugas-distribusi-modal">Pilih Petugas Distribusi</button>

    {% csrf_token %}
    <input type="submit" value="Tambah">
</form>

<div id="pilih-kendaraan-modal" class="modal fade pilih-kendaraan-modal" tabindex="-1" role="dialog" aria-labelledby="pilihKendaraanLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pilihKendaraanLabel">Pilih Kendaraan</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <th>Nomor Kendaraan</th>
                        <th>Nama Kendaraan</th>
                        <th>Jenis Kendaraan</th>
                        <th>Berat Maksimum (kg)</th>
                        <th>Action</th>
                    </tr>

                    {% for kendaraan in kendaraans %}

                    <tr>
                        <td>{{ kendaraan.0 }}</td>
                        <td>{{ kendaraan.1 }}</td>
                        <td>{{ kendaraan.2 }}</td>
                        <td>{{ kendaraan.3 }}</td>
                        <td>
                            <button class="pilih-kendaraan" type="button" value="{{ kendaraan.0 }}">Pilih</button>
                        </td>
                    </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

<div id="pilih-petugas-distribusi-modal" class="modal fade pilih-petugas-distribusi-modal" tabindex="-2" role="dialog" aria-labelledby="pilihPetugasDistribusiLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pilihPetugasDistribusiLabel">Pilih Petugas Distribusi</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table>
                    <tr>
                        <th>Nama</th>
                        <th>Nomor SIM</th>
                        <th>Action</th>
                    </tr>

                    {% for distributor in distributors %}

                    <tr>
                        <td>{{ distributor.1 }}</td>
                        <td>{{ distributor.2 }}</td>
                        <td>
                            <button class="pilih-petugas-distribusi" type="button" value="{{ distributor.0 }}">Pilih</button>
                        </td>
                    </tr>

                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

<table>
    <tr>
        <th>Kode Batch</th>
        <th>Kendaraan</th>
        <th>Petugas Distribusi</th>
        <th>Asal</th>
        <th>Tujuan</th>
    </tr>

    {% for pengiriman in pengirimans %}

    <tr>
        <td>{{ pengiriman.0 }}</td>
        <td>{{ pengiriman.1 }}</td>
        <td>{{ pengiriman.2 }}</td>
        <td>{{ pengiriman.3 }}</td>
        <td>{{ pengiriman.4 }}</td>
    </tr>

    {% endfor %}

</table>

{% endblock body %}

{% block script %}
<script src="{% static 'pengiriman/script.js' %}"></script>
{% endblock script %}

pengiriman/templates/pengiriman/batch_detail.html
{% extends 'pengguna/base.html' %}

{% block body %}

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<br><br>

<h3>Nomor Transaksi: {{ no_transaksi }}</h3>

<table>
    <tr>
        <th>Kode Batch</th>
        <th>Kendaraan</th>
        <th>Petugas Distribusi</th>
        <th>Asal</th>
        <th>Tujuan</th>
    </tr>

    {% for i in data %}
    <tr>
        <td>{{ i.0 }}</td>
        <td>{{ i.1 }}</td>
        <td>{{ i.2 }}</td>
        <td>{{ i.3 }}</td>
        <td>{{ i.4 }}</td>
    </tr>
    {% endfor %}
</table>


{% endblock body %}

pengiriman/templates/pengiriman/kendaraan.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if request.session.role == 'admin' %}

<a href="{% url 'pengiriman:add_kendaraan' %}">Tambah kendaraan</a>
<table>
    <tr>
        <th>Nomor Kendaraan</th>
        <th>Nama Kendaraan</th>
        <th>Jenis Kendaraan</th>
        <th>Berat Maksimum (kg)</th>
        <th>Action</th>
    </tr>

    {% for kendaraan in kendaraans %}

    <tr>
        <td>{{ kendaraan.0 }}</td>
        <td>{{ kendaraan.1 }}</td>
        <td>{{ kendaraan.2 }}</td>
        <td>{{ kendaraan.3 }}</td>
        <td>
            <form action="{% url 'pengiriman:update_kendaraan' kendaraan.0 %}">
                <input type="submit" value="Update">
            </form>
            <form action="{% url 'pengiriman:delete_kendaraan' kendaraan.0 %}">
                <input type="submit" value="Delete">
            </form>
        </td>
    </tr>

    {% endfor %}
</table>

{% elif request.session.role == 'distribusi' %}

<table>
    <tr>
        <th>Nomor Kendaraan</th>
        <th>Nama Kendaraan</th>
        <th>Jenis Kendaraan</th>
        <th>Berat Maksimum (kg)</th>
    </tr>

    {% for kendaraan in kendaraans %}

    <tr>
        <td>{{ kendaraan.0 }}</td>
        <td>{{ kendaraan.1 }}</td>
        <td>{{ kendaraan.2 }}</td>
        <td>{{ kendaraan.3 }}</td>
    </tr>

    {% endfor %}

</table>

{% else %}

<p>Role yang bisa mengakses hanya admin dan petugas distribusi</p>

{% endif %}

{% endblock body %}

pengiriman/templates/pengiriman/kendaraan_add.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<form method="POST" action="{% url 'pengiriman:add_kendaraan' %}">
    {% csrf_token %}
    
    <input type="text" name="nomor" placeholder="Nomor" required>
    <input type="text" name="nama" placeholder="Nama" required>
    <input type="text" name="jenis" placeholder="Jenis Kendaraan" required>
    <input type="number" name="berat" placeholder="Berat Maksimum" required>
    <button type="submit">Simpan</button>
</form>

{% endblock body %}

pengiriman/templates/pengiriman/kendaraan_update.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<h3>Update Kendaraan {{ kendaraan.0 }}</h3>
<form method="POST" action="{% url 'pengiriman:update_kendaraan' kendaraan.0 %}">
    {% csrf_token %}
    
    <input type="text" name="nomor" placeholder="Nomor" value="{{ kendaraan.0 }}" required>
    <input type="text" name="nama" placeholder="Nama" value="{{ kendaraan.1 }}" required>
    <input type="text" name="jenis" placeholder="Jenis Kendaraan" value="{{ kendaraan.2 }}" required>
    <input type="number" name="berat" placeholder="Berat Maksimum" value="{{ kendaraan.3 }}" required>
    <button type="submit">Simpan</button>
</form>

{% endblock body %}

pengiriman/templates/pengiriman/lokasi.html
{% extends 'pengguna/base.html' %}

{% block body %}

<a href="{% url 'pengiriman:add_lokasi' %}">Tambah lokasi</a>
<table>
    <tr>
        <th>ID Lokasi</th>
        <th>Provinsi</th>
        <th>Kabupaten/Kota</th>
        <th>Kecamatan</th>
        <th>Kelurahan</th>
        <th>Jalan</th>
        <th>Action</th>
    </tr>

    {% for lokasi in lokasis %}

    <tr>
        <td>{{ lokasi.0 }}</td>
        <td>{{ lokasi.1 }}</td>
        <td>{{ lokasi.2 }}</td>
        <td>{{ lokasi.3 }}</td>
        <td>{{ lokasi.4 }}</td>
        <td>{{ lokasi.5 }}</td>
        <td>
            <form action="{% url 'pengiriman:update_lokasi' lokasi.0 %}">
                <input type="submit" value="Update">
            </form>
        </td>
    </tr>

    {% endfor %}
</table>

{% endblock body %}

pengiriman/templates/pengiriman/lokasi_add.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<form method="POST" action="{% url 'pengiriman:add_lokasi' %}">
    {% csrf_token %}
    
    <input type="text" name="id" value="{{ id_lokasi }}" readonly>

    <select name="provinsi">
        <option value="Aceh">Aceh</option>
        <option value="Bali">Bali</option>
        <option value="Banten">Banten</option>
        <option value="Bengkulu">Bengkulu</option>
        <option value="Daerah Istimewa Yogyakarta">Daerah Istimewa Yogyakarta</option>
        <option value="DKI Jakarta">DKI Jakarta</option>
        <option value="Gorontalo">Gorontalo</option>
        <option value="Jambi">Jambi</option>
        <option value="Jawa Barat">Jawa Barat</option>
        <option value="Jawa Tengah">Jawa Tengah</option>
        <option value="Jawa Timur">Jawa Timur</option>
        <option value="Kalimantan Barat">Kalimantan Barat</option>
        <option value="Kalimantan Selatan">Kalimantan Selatan</option>
        <option value="Kalimantan Tengah">Kalimantan Tengah</option>
        <option value="Kalimantan Timur">Kalimantan Timur</option>
        <option value="Kalimantan Utara">Kalimantan Utara</option>
        <option value="Kepulauan Bangka Belitung">Kepulauan Bangka Belitung</option>
        <option value="Kepulauan Riau">Kepulauan Riau</option>
        <option value="Lampung">Lampung</option>
        <option value="Maluku">Maluku</option>
        <option value="Maluku Utara">Maluku Utara</option>
        <option value="Nusa Tenggara Barat">Nusa Tenggara Barat</option>
        <option value="Nusa Tenggara Timur">Nusa Tenggara Timur</option>
        <option value="Papua">Papua</option>
        <option value="Papua Barat">Papua Barat</option>
        <option value="Riau">Riau</option>
        <option value="Sulawesi Barat">Sulawesi Barat</option>
        <option value="Sulawesi Selatan">Sulawesi Selatan</option>
        <option value="Sulawesi Tengah">Sulawesi Tengah</option>
        <option value="Sulawesi Tenggara">Sulawesi Tenggara</option>
        <option value="Sulawesi Utara">Sulawesi Utara</option>
        <option value="Sumatera Barat">Sumatera Barat</option>
        <option value="Sumatera Selatan">Sumatera Selatan</option>
        <option value="Sumatera Utara">Sumatera Utara</option>
    </select>
    <input type="text" name="kabkot" placeholder="Kabupaten/Kota" required>
    <input type="text" name="kecamatan" placeholder="Kecamatan" required>
    <input type="text" name="kelurahan" placeholder="Kelurahan" required>
    <input type="text" name="jalan" placeholder="Jalan" required>
    <button type="submit">Simpan</button>
</form>

{% endblock body %}