faskes/urls.py
from django.urls import path

from . import views

app_name = 'faskes'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.add_faskes, name='addfaskes'),
    path('update', views.update_faskes, name='updatefaskes'),
    path('delete', views.delete_faskes, name='deletefaskes'),
]

pengguna/urls.py
from django.urls import path

from . import views

app_name = 'pengguna'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('registerSupplier', views.registerSupplier, name='registerSupplier'),
    path('registerPetugasFaskes', views.registerPetugasFaskes ,name='registerPetugasFaskes'),
    path('registerPetugasDistribusi', views.registerPetugasDistribusi, name='registerPetugasDistribusi'),
    path('registerAdminSatgas', views.registerAdminSatgas, name='registerAdminSatgas'),
    path('wrong_role', views.wrong_role, name='wrong_role'),
    path('updateProfile',views.updateProfile,name="UpdateProfile"),
    path('landing',views.afterLogin,name="AfterLogin")
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pengguna.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('trigger3/',include('trigger3.urls')),
    path('trigger6/', include ('trigger6.urls')),
    path('faskes/', include('faskes.urls')),
    path('warehouse/', include('warehouse.urls'))
]

trigger3/urls.py
from django.urls import path

from . import views

app_name = 'trigger3'

urlpatterns = [
    path('createpesanansumberdaya', views.createPesananSD, name='CreatePesananSumberDaya'),
    path('readpesanansumberdaya', views.readPesanan, name='ReadPesananSumberDaya'),
    path('readpesanansumberdaya/detail/<int:idPesanan>', views.detailPesanan, name='DetailPesanan'),
    path('readpesanansumberdaya/riwayatstatus/<int:idPesanan>',views.riwayatStatus,name='RiwayatStatus'),
    path('readpesanansumberdaya/updatepesanan/<int:idPesanan>', views.updatePesanan, name='UpdatePesanan'),
    path('SupplierReadPesanan',views.SupplierReadPesanan,name='SupplierReadPesanan'),
    path('SupplierReadPesanan/detail/<int:idPesanan>',views.detailPesananSupplier,name='DetailPesananSupplier'),
    path('SupplierReadPesanan/riwayatstatus/<int:idPesanan>',views.riwayatStatusSupplier,name='RiwayatStatusSupplier'),
    path('createstockfaskes',views.createStockFaskes, name='CreateStockFaskes'),
    path('liststockfaskes',views.listStockFaskes, name='ListStockFaskes'),
    path('liststockfaskes/updatestock/<str:kodeFaskes>/<str:namaFaskes>/<str:namaItem>', views.updateStockFaskes, name='UpdateStockFaskes'),
    path('liststockfaskespetugas',views.ListStockFaskesPetugas,name='ListStockFaskesPetugas')
]

trigger6/urls.py
from django.urls import path

from . import views

app_name = 'trigger6'

urlpatterns = [
    path('WarehouseStockCreate', views.WarehouseStockCreate, name = 'WarehouseStockCreate'),
    path('WarehouseStockRead', views.WarehouseStockRead, name = 'WarehouseStockRead'),
    path('WarehouseStockUpdate/<str:warehouse>/<str:item>', views.WarehouseStockUpdate, name = 'WarehouseStockUpdate'),
    path('WarehouseStockReadFaskes', views.WarehouseStockReadFaskes, name = 'WarehouseStockReadFaskes'),

    path('RiwayatStatusBatchCreate', views.RiwayatStatusBatchCreate, name = 'RiwayatStatusBatchCreate'),
    path('RiwayatStatusBatchRead', views.RiwayatStatusBatchRead, name = 'RiwayatStatusBatchRead')
]

warehouse/urls.py
from django.urls import path

from . import views

app_name = 'warehouse'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.add_warehouse, name='addwarehousesatgas'),
    path('update', views.update_warehouse, name='updatewarehousesatgas'),
    path('delete', views.delete_warehouse, name='deletewarehousesatgas'),
]

pengguna/models.py
from django.db import models

# Create your models here.

pengguna/views.py
from django.shortcuts import render, redirect
from django.db import InternalError, connection
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, "pengguna/index.html")

def afterLogin(request):
    if request.session['role'] == "supplier":
        print("MASUK")
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT nama_organisasi FROM SUPPLIER WHERE username='{request.session['username']}';
            """)
            dataTambahan = cursor.fetchall()
    elif request.session['role'] == "distribusi":
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT No_SIM FROM PETUGAS_DISTRIBUSI WHERE username='{request.session['username']}';
            """)
            dataTambahan = cursor.fetchall()
    else:
        dataTambahan=[]
        
    with connection.cursor() as cursor:
        cursor.execute(f"""
        SELECT * FROM PENGGUNA
        WHERE username='{request.session['username']}'
        """)
        data = cursor.fetchall()
    context = {
        "data":data,
        "dataTambahan":dataTambahan
    }
    return render(request, "pengguna/AfterLogin.html",context)

def wrong_role(request):
    return render(request, "pengguna/wrong_role.html")

def login(request):
    if request.session.get("username", False):
        return redirect("pengguna:index")

    if request.method == "POST":
        found = False
        role = None

        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT p.username,
                CASE
                    WHEN a.username IS NOT null THEN 'admin'
                    WHEN f.username IS NOT null THEN 'faskes'
                    WHEN d.username IS NOT null THEN 'distribusi'
                    WHEN s.username IS NOT null THEN 'supplier'
                END AS role
                FROM pengguna AS p
                    LEFT JOIN admin_satgas AS a ON a.username=p.username
                    LEFT JOIN petugas_faskes AS f ON f.username=p.username
                    LEFT JOIN petugas_distribusi AS d ON d.username=p.username
                    LEFT JOIN supplier AS s ON s.username=p.username
                WHERE p.username='{request.POST["username"]}'
                AND p.password='{request.POST["password"]}'
                """)

            row = cursor.fetchall()
            print(row)
            if (len(row) != 0): # Berhasil login

                # Rolenya ada: 'admin', 'faskes', 'distribusi', 'supplier' CASE SENSITIVE!!!

                request.session["username"] = row[0][0]
                request.session["role"] = row[0][1]
                return redirect("pengguna:AfterLogin")

            else: # Gagal login
                messages.add_message(request, messages.WARNING, "Maaf, username atau password salah.")

    return render(request, "pengguna/login.html")

def logout(request):
    request.session.pop("username", None)
    request.session.pop("role", None)
    return redirect("pengguna:index")

def registerSupplier(request):

    if request.method == "POST":
        with connection.cursor() as cursor:
            username = request.POST["username"]

            cursor.execute(f"""
                SELECT FROM PENGGUNA WHERE username = '{request.POST["username"]}'
            """)

            # Jika tidak terdapat username yang sama pada PENGGUNA
            if (len(cursor.fetchall())== 0):
                cursor.execute(f"""
                    INSERT INTO PENGGUNA VALUES 
                    ('{request.POST['username']}','{request.POST['password']}','{request.POST['nama']}',
                    '{request.POST['alamat_kel']}','{request.POST['alamat_kec']}','{request.POST['alamat_kabkot']}',
                    '{request.POST['alamat_prov']}','{request.POST['no_telepon']}')
                """)

                cursor.execute(f"""
                    INSERT INTO SUPPLIER VALUES
                    ('{request.POST['username']}','{request.POST['nama']}')
                """)

                messages.add_message(request,messages.SUCCESS, f"Registrasi Supplier Berhasil Dilakukan, Silahkan Login")

                return redirect("pengguna:login")
            else:
                messages.add_message(request, messages.WARNING, f"{request.POST['username']} sudah terdaftar sebelumnya")

    return render(request, "pengguna/RegisterSupplier.html")

def registerPetugasFaskes(request):

    if request.method == "POST":
        with connection.cursor() as cursor:
            username = request.POST["username"]

            cursor.execute(f"""
                SELECT FROM PENGGUNA WHERE username = '{request.POST["username"]}'
            """)

            # Jika tidak terdapat username yang sama pada PENGGUNA
            if (len(cursor.fetchall())== 0):
                cursor.execute(f"""
                    INSERT INTO PENGGUNA VALUES 
                    ('{request.POST['username']}','{request.POST['password']}','{request.POST['nama']}',
                    '{request.POST['alamat_kel']}','{request.POST['alamat_kec']}','{request.POST['alamat_kabkot']}',
                    '{request.POST['alamat_prov']}','{request.POST['no_telepon']}')
                """)

                cursor.execute(f"""
                    INSERT INTO PETUGAS_FASKES VALUES
                    ('{request.POST['username']}')
                """)

                messages.add_message(request,messages.SUCCESS, f"Registrasi Petugas Faskes Berhasil Dilakukan, Silahkan Login")

                return redirect("pengguna:login")
            else:
                messages.add_message(request, messages.WARNING, f"{request.POST['username']} sudah terdaftar sebelumnya")

    return render(request, "pengguna/RegisterPetugasFaskes.html")

def registerPetugasDistribusi(request):   
    if request.method == "POST":
        with connection.cursor() as cursor:
            username = request.POST["username"]

            cursor.execute(f"""
                SELECT FROM PENGGUNA WHERE username = '{request.POST["username"]}'
            """)

            # Jika tidak terdapat username yang sama pada PENGGUNA
            if (len(cursor.fetchall())== 0):
                cursor.execute(f"""
                    INSERT INTO PENGGUNA VALUES 
                    ('{request.POST['username']}','{request.POST['password']}','{request.POST['nama']}',
                    '{request.POST['alamat_kel']}','{request.POST['alamat_kec']}','{request.POST['alamat_kabkot']}',
                    '{request.POST['alamat_prov']}','{request.POST['no_telepon']}')
                """)

                cursor.execute(f"""
                    INSERT INTO PETUGAS_DISTRIBUSI VALUES
                    ('{request.POST['username']}','{request.POST['no_sim']}')
                """)

                messages.add_message(request,messages.SUCCESS, f"Registrasi Petugas Distribusi Berhasil Dilakukan, Silahkan Login")

                return redirect("pengguna:login")
            else:
                messages.add_message(request, messages.WARNING, f"{request.POST['username']} sudah terdaftar sebelumnya")

    return render(request, "pengguna/RegisterPetugasDistribusi.html")

def registerAdminSatgas(request):
    if request.method == "POST":
        print("UHUY")
        with connection.cursor() as cursor:
            username = request.POST["username"]

            cursor.execute(f"""
                SELECT FROM PENGGUNA WHERE username = '{request.POST["username"]}'
            """)

            # Jika tidak terdapat username yang sama pada PENGGUNA
            if (len(cursor.fetchall())== 0):
                cursor.execute(f"""
                    INSERT INTO PENGGUNA VALUES 
                    ('{request.POST['username']}','{request.POST['password']}','{request.POST['nama']}',
                    '{request.POST['alamat_kel']}','{request.POST['alamat_kec']}','{request.POST['alamat_kabkot']}',
                    '{request.POST['alamat_prov']}','{request.POST['no_telepon']}')
                """)

                cursor.execute(f"""
                    INSERT INTO ADMIN_SATGAS VALUES
                    ('{request.POST['username']}')
                """)

                messages.add_message(request,messages.SUCCESS, f"Registrasi Admin Satgas Berhasil Dilakukan, Silahkan Login")

                return redirect("pengguna:login")
            else:
                messages.add_message(request, messages.WARNING, f"{request.POST['username']} sudah terdaftar sebelumnya")

    return render(request, "pengguna/RegisterAdminSatgas.html")

def updateProfile(request):
    if request.session['role'] == "supplier":
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT nama_organisasi FROM SUPPLIER WHERE username='{request.session['username']}';
            """)
            dataTambahan = cursor.fetchall()
    elif request.session['role'] == "distribusi":
        with connection.cursor() as cursor:
            cursor.execute(f"""
            SELECT No_SIM FROM PETUGAS_DISTRIBUSI WHERE username='{request.session['username']}';
            """)
            dataTambahan = cursor.fetchall()
    else:
        dataTambahan=[]
    with connection.cursor() as cursor:
        cursor.execute(f"""
        SELECT * FROM PENGGUNA WHERE username='{request.session['username']}';
        """)
        data = cursor.fetchall()
    print(data)
    context = {
        "data":data,
        "dataTambahan":dataTambahan,
        "role":request.session['role']
    }
    if request.method == "POST":
        with connection.cursor() as cursor:
            cursor.execute(f"""
            UPDATE PENGGUNA SET
            password = '{request.POST['password']}',
            nama = '{request.POST['nama']}',
            alamat_kel = '{request.POST['kelurahan']}',
            alamat_kec = '{request.POST['kecamatan']}',
            alamat_kabkot = '{request.POST['kabupaten']}',

pengguna/templates/pengguna/AfterLogin.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if request.session.username %}
<div class="container-xl">
    <h1>{{ request.session.username }}</h1>
    <p><strong>Role:</strong> {{ request.session.role }}</p>
    {% for i in data %} 
        <p><strong>Nama Lengkap: </strong> {{i.2}}</p>
        <p><strong>Kelurahan: </strong>{{i.3}}</p>
        <p><strong>Kecamatan: </strong>{{i.4}}</p>
        <p><strong>Kabupaten: </strong>{{i.5}}</p>
        <p><strong>Provinsi: </strong>{{i.6}}</p>
        <p><strong>No Telepon: </strong>{{i.7}}</p>
        {% if request.session.role == "supplier" %}
        <p><strong>Nama Organisasi: </strong> {{dataTambahan.0.0}}</p>
        {% elif request.session.role == "distribusi" %}
        <p><strong>No SIM: </strong> {{dataTambahan.0.0}}</p>
        {% endif %}
    {% endfor %}
    <a class="btn btn-dark" href="{% url 'pengguna:UpdateProfile' %}">Edit Profile</a>
    {% else %}
    <h1>Kayanya bagusan diisi homepage(landing)***</h1>
</div>
{% endif %}
{% endblock body %}

pengguna/templates/pengguna/base.html
<!DOCTYPE html>
<html>
    {% load static %}
    <head>
        <title>SIDIA-E5</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- bootstrap  -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        {% block head %}
        {% endblock head %}
    </head>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      {% if request.session.username %}
        <a class="navbar-brand" href="/landing">SIDIA E5</a>
      {% else %}
      <a class="navbar-brand" href="/">SIDIA E5</a>
      {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="collapsibleNavbar">
          <ul class="navbar-nav">
            {% if request.session.role == 'faskes' %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'pengiriman:batch' %}">Batch Pengiriman</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'trigger6:WarehouseStockReadFaskes' %}">Stock Warehouse Satgas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'trigger3:ListStockFaskesPetugas' %}">Stock Faskes</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Permohonan Sumber Daya
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Buat Permohonan Sumber Daya</a>
                <a class="dropdown-item" href="#">List Permohonan Sumber Daya</a>
                <a class="dropdown-item" href="#">List Riwayat Status Permohonan Sumber Daya</a>
              </div>
            </li>
            {% elif request.session.role == 'admin' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Permohonan Sumber Daya
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">List Permohonan Sumber Daya</a>
                  <a class="dropdown-item" href="#">Buat Riwayat Status Permohonan Sumber Daya</a>
                  <a class="dropdown-item" href="#">List Riwayat Status Permohonan Sumber Daya</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Item Sumber Daya</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pesanan Sumber Daya
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger3:CreatePesananSumberDaya' %}">Buat Pesanan Sumber Daya</a>
                  <a class="dropdown-item" href="{% url 'trigger3:ReadPesananSumberDaya' %}">List Pesanan Sumber Daya</a>
                  <a class="dropdown-item" href="#">List Riwayat Status Pesanan Sumber Daya</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kendaraan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengiriman:add_kendaraan' %}">Buat Kendaraan</a>
                  <a class="dropdown-item" href="{% url 'pengiriman:kendaraan' %}">List Kendaraan</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Batch Pengiriman
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengiriman:batch' %}">List Batch Pengiriman</a>
                  <a class="dropdown-item" href="{% url 'trigger6:RiwayatStatusBatchCreate' %}">Buat Riwayat Status Batch
                    Pengiriman</a>
                  <a class="dropdown-item" href="{% url 'trigger6:RiwayatStatusBatchRead' %}">List Riwayat Status Batch
                    Pengiriman</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Lokasi
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengiriman:add_lokasi' %}">Buat Lokasi</a>
                  <a class="dropdown-item" href="{% url 'pengiriman:lokasi' %}">List Lokasi</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Fasilitas Kesehatan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'faskes:addfaskes' %}">Buat Faskes</a>
                  <a class="dropdown-item" href="{% url 'faskes:index' %}">List Faskes</a>
                  <a class="dropdown-item" href="{% url 'trigger3:CreateStockFaskes' %}">Buat Stock Faskes</a>
                  <a class="dropdown-item" href="{% url 'trigger3:ListStockFaskes' %}">List Stock Faskes</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Warehouse Satgas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'warehouse:addwarehousesatgas' %}">Buat Warehouse Satgas</a>
                  <a class="dropdown-item" href="{% url 'warehouse:index' %}">List Warehouse Satgas</a>
                  <a class="dropdown-item" href="{% url 'trigger6:WarehouseStockCreate' %}">Buat Stock Warehouse Satgas</a>
                  <a class="dropdown-item" href="{% url 'trigger6:WarehouseStockRead' %}">List Warehouse Satgas</a>
                </div>
            </li>
            {% elif request.session.role == 'supplier' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Item Sumber Daya
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Buat Item Sumber Daya</a>
                  <a class="dropdown-item" href="#">List Item Sumber Daya</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pesanan Sumber Daya
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'trigger3:SupplierReadPesanan' %}">List Pesanan Sumber Daya</a>
                  <a class="dropdown-item" href="#">Ubah Riwayat Pesanan Sumber Daya</a>
                  <a class="dropdown-item" href="#">List Riwayat Pesanan Sumber Daya</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'faskes:index' %}">Fasilitas Kesehatan</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Warehouse
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'warehouse:index' %}">List Warehouse Satgas</a>
                  <a class="nav-link" href="{% url 'trigger6:WarehouseStockReadFaskes' %}">Stock Warehouse Satgas</a>
                </div>
            </li>
            {% elif request.session.role == 'distribusi' %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Kendaraan
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengiriman:kendaraan' %}">List Kendaraan</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Batch Pengiriman
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengiriman:batch' %}">List Batch Pengiriman</a>
                  <a class="dropdown-item" href="{% url 'trigger6:RiwayatStatusBatchRead' %}">List Riwayat Status Batch Pengiriman</a>
                </div>
            </li>
            {% endif %}

          </ul>
          {% if request.session.username %}
          <ul class="navbar-nav">
            <!-- Logout -->
            <li class="nav-item">
                <a style="color: white;" class="nav-link" href="{% url 'pengguna:logout' %}">Logout</a></li>
            </li>
            <!-- Hello, {user} -->
            <li class="nav-item">
                <a style="color: white; font-weight: bold;" class="nav-link" href="/landing">{{ request.session.username }}</a></li>
            </li>
          </ul>
          {% else %}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Register
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'pengguna:registerSupplier' %}">Supplier</a>
                  <a class="dropdown-item" href="{% url 'pengguna:registerPetugasFaskes' %}">Petugas Faskes</a>
                  <a class="dropdown-item" href="{% url 'pengguna:registerPetugasDistribusi' %}">Petugas Distribusi</a>
                  <a class="dropdown-item" href="{% url 'pengguna:registerAdminSatgas' %}">Admin Satgas</a>
              </div>
            </li>
            <li class="nav-item">
                <a style="color: white" class="nav-link"  href="{% url 'pengguna:login' %}" style="margin-right: 100px;">Login</a></li>
            </li>
        </ul>
          {% endif %}
        </div>
      </li>
  </div>
</nav>

<body>
  {% block body %}
  {% endblock body %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
    integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
    crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>

</html>

pengguna/templates/pengguna/index.html
{% extends 'pengguna/base.html' %}

{% block body %}

<div class="container-xl" style="text-align: center;">
    <h1 style="text-align: center;">SIDIA E05</h1>
    <p>Aryaputra Athallah</p>
    <p>Naufal Sani</p>
    <p>Kevin Dharmawan</p> 
    <p>William</p>
</div>
{% endblock body %}