faskes/urls.py
from django.urls import path

from . import views

app_name = 'faskes'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.add_faskes, name='addfaskes'),
    path('update', views.update_faskes, name='updatefaskes'),
    path('delete', views.delete_faskes, name='deletefaskes'),
]

sidia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pengguna.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('trigger3/',include('trigger3.urls')),
    path('trigger6/', include ('trigger6.urls')),
    path('faskes/', include('faskes.urls')),
    path('warehouse/', include('warehouse.urls'))
]

faskes/models.py
from django.db import models

# Create your models here.

faskes/views.py
from django.shortcuts import render, redirect
from django.db import IntegrityError, InternalError, OperationalError, connection
from django.contrib import messages

# Create your views here.

def index(request):
    if request.session["role"] == "admin" or request.session["role"] == "supplier":
        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT kode_faskes_nasional, CONCAT_WS(', ', jalan_no, kelurahan, kecamatan, kabkot, provinsi) as lokasi, nama, nama_tipe
                FROM faskes f JOIN lokasi l ON l.id = f.id_lokasi 
                JOIN tipe_faskes tf ON tf.kode = f.kode_tipe_faskes
                JOIN pengguna p ON f.username_petugas = p.username
            """)

            context = {"faskeses" : cursor.fetchall()}
    else:
        context = {}

    return render(request, "faskes/index.html", context)

def add_faskes(request):
    if request.session["role"] == "admin":
        if request.method == "POST":
            if (request.POST.get('kode_faskes') is None or request.POST.get('id_lokasi') is None or request.POST.get('username_petugas') is None or request.POST.get('kode_tipe_faskes') is None):
                messages.add_message(request, messages.WARNING, "Isi permintaan penambahan tidak valid")
            if (request.POST['kode_faskes'] == "" or request.POST['id_lokasi'] == "" or request.POST['username_petugas'] == "" or request.POST['kode_tipe_faskes'] == ""):
                messages.add_message(request, messages.WARNING, "Terdapat  data  yang  belum  diisi,  silahkan  lengkapi  data terlebih dahulu")
            else :
                try:
                    with connection.cursor() as cursor:

                        cursor.execute(f"""
                            INSERT INTO faskes VALUES 
                            ('{request.POST['kode_faskes']}',
                            '{request.POST['id_lokasi']}',
                            '{request.POST['username_petugas']}',
                            '{request.POST['kode_tipe_faskes']}')
                        """)

                        messages.add_message(request, messages.SUCCESS, "Data Fasilitas Kesehatan Telah Disimpan!")

                        return redirect("faskes:index")
                except IntegrityError:
                    messages.add_message(request, messages.WARNING, f"Data Fasilitas Kesehatan dengan kode {request.POST['kode_faskes']} sudah terdaftar")

        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT id, CONCAT_WS(', ', jalan_no, kelurahan, kecamatan, kabkot, provinsi) as alamat
                FROM lokasi
            """)

            context = {"lokasis" : cursor.fetchall()}

            cursor.execute(f"""
                SELECT username, nama 
                FROM petugas_faskes NATURAL JOIN pengguna 
                WHERE username NOT IN (SELECT username_petugas FROM faskes)
            """)

            context["petugas_faskeses"] = cursor.fetchall()

            cursor.execute(f"""
                SELECT kode, nama_tipe FROM tipe_faskes
            """)

            context["tipe_faskeses"] = cursor.fetchall()

        return render(request, "faskes/addfaskes.html", context)
    elif request.session["role"] == "supplier":
        messages.add_message(request, messages.WARNING, f"Hanya admin yang dapat menambahkan data faskes")
        return redirect("faskes:index")
    else:
        return redirect("faskes:index")

def update_faskes(request):
    if request.session["role"] == "admin":
        if request.method == "POST":
            if (request.POST.get('kode_faskes') is None or request.POST.get('kode_faskes') == ""):
                messages.add_message(request, messages.WARNING, "Isi permintaan update tidak valid")
                redirect("faskes:index")
            elif (request.POST.get('id_lokasi') is None or request.POST.get('username_petugas') is None or request.POST.get('kode_tipe_faskes') is None):
                messages.add_message(request, messages.WARNING, "Isi permintaan update tidak valid")
            if (request.POST['id_lokasi'] == "" or request.POST['username_petugas'] == "" or request.POST['kode_tipe_faskes'] == ""):
                messages.add_message(request, messages.WARNING, "Terdapat  data  yang  belum  diisi,  silahkan  lengkapi  data terlebih dahulu")
            else :
                try:
                    with connection.cursor() as cursor:

                        cursor.execute(f"""
                            UPDATE faskes
                            SET id_lokasi = '{request.POST['id_lokasi']}',
                            username_petugas = '{request.POST['username_petugas']}',
                            kode_tipe_faskes = '{request.POST['kode_tipe_faskes']}'
                            WHERE kode_faskes_nasional = '{request.POST['kode_faskes']}'
                        """)

                        messages.add_message(request, messages.SUCCESS, "Data Fasilitas Kesehatan Telah Diupdate!")

                        return redirect("faskes:index")
                
                except OperationalError:
                    messages.add_message(request, messages.WARNING, f"Tidak ada data Fasilitas Kesehatan dengan kode {request.POST['kode_faskes']}")

        with connection.cursor() as cursor:

            cursor.execute(f"""
                SELECT kode_faskes_nasional, id_lokasi, username, nama, kode_tipe_faskes 
                FROM faskes f JOIN pengguna p ON p.username = f.username_petugas
                WHERE kode_faskes_nasional = '{request.GET['kode_faskes']}'
            """)

            data = cursor.fetchone()

            if (data is None):
                messages.add_message(request, messages.WARNING, f"Tidak ada data Fasilitas Kesehatan dengan kode {request.GET['kode_faskes']}")
                return redirect("faskes:index")

            context = {"current" : data}

            cursor.execute(f"""
                SELECT id, CONCAT_WS(', ', jalan_no, kelurahan, kecamatan, kabkot, provinsi) as alamat
                FROM lokasi
            """)

            context["lokasis"] = cursor.fetchall()

            cursor.execute(f"""
                SELECT username, nama 
                FROM petugas_faskes NATURAL JOIN pengguna 
                WHERE username NOT IN (SELECT username_petugas FROM faskes)
            """)

            context["petugas_faskeses"] = cursor.fetchall()

            cursor.execute(f"""
                SELECT kode, nama_tipe FROM tipe_faskes
            """)

            context["tipe_faskeses"] = cursor.fetchall()

        return render(request, "faskes/updatefaskes.html", context)
    elif request.session["role"] == "supplier":
        messages.add_message(request, messages.WARNING, f"Hanya admin yang dapat mengupdate data faskes")
        return redirect("faskes:index")
    else:
        return redirect("faskes:index")

def delete_faskes(request):
    if request.session["role"] == "admin":
        if request.method == "POST":
            if (request.POST.get('kode_faskes') is None or request.POST.get('kode_faskes') == ""):
                messages.add_message(request, messages.WARNING, "Isi permintaan penghapusan tidak valid")
            with connection.cursor() as cursor:

                cursor.execute(f"""
                    DELETE FROM faskes
                    WHERE kode_faskes_nasional = '{request.POST['kode_faskes']}'
                """)

                messages.add_message(request, messages.SUCCESS, "Data Fasilitas Kesehatan telah Dihapus!")
        
        else:
            messages.add_message(request, messages.WARNING, f"Metode Permintaan tidak valid")
        
        return redirect("faskes:index")
    elif request.session["role"] == "supplier":
        messages.add_message(request, messages.WARNING, f"Hanya admin yang dapat menghapus data faskes")
        return redirect("faskes:index")
    else:
        return redirect("faskes:index")

faskes/templates/faskes/addfaskes.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == "success" %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

<h2>Form Tambah Fasilitas Kesehatan</h2>

<form class="needs-validation" method="POST" action="{% url 'faskes:addfaskes' %}" novalidate>
    {% csrf_token %}
    <div class="form-group">
        <label for="kode_faskes">Kode Faskes:</label>
        <input class="form-control" type="text" id="kode_faskes" name="kode_faskes" required>
        <div class="invalid-feedback">
            Data Kode Faskes belum terisi
        </div>
    </div>
    
    <div class="form-group">
        <label for="id_lokasi">Id Lokasi:</label>
        <select class="form-control" name="id_lokasi" id="id_lokasi" onchange=changelokasiaddress() required>
            <option value="" selected>Id Lokasi</option>
            {% for lokasi in lokasis %}
                <option value="{{ lokasi.0 }}">{{ lokasi.0 }}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            Data Id Lokasi belum terisi
        </div>
    </div>

    <div class="form-group">
        <label for="lokasiaddress">Lokasi</label>
        <input class="form-control" type="text" id="lokasiaddress" disabled>
    </div>

    <div class="form-group">
        <label for="username_petugas">Petugas Faskes:</label>
        <select class="form-control" name="username_petugas" id="username_petugas" required>
            <option value="" selected>Petugas faskes</option>
            {% for petugas_faskes in petugas_faskeses %}
                <option value="{{ petugas_faskes.0 }}">{{ petugas_faskes.1 }}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            Data Petugas Faskes belum terisi
        </div>
    </div>

    <div class="form-group">
        <label for="kode_tipe_faskes">Kode Tipe Faskes:</label>
        <select class="form-control" name="kode_tipe_faskes" id="kode_tipe_faskes" onchange=changetipefaskes() required>
            <option value="" selected>Kode Tipe Faskes</option>
            {% for tipe_faskes in tipe_faskeses %}
                <option value="{{ tipe_faskes.0 }}">{{ tipe_faskes.0 }}</option>
            {% endfor %}
        </select>
        <div class="invalid-feedback">
            Data Kode Tipe Faskes belum terisi
        </div>
    </div>

    <div class="form-group">
        <label for="tipefaskesname">Tipe Faskes:</label>
        <input class="form-control" type="text" id="tipefaskesname" disabled>
    </div>

    <input class="btn btn-primary" type="submit" value="Simpan">
    <a class="btn btn-danger" href="{% url 'faskes:index' %}">batal</a>
</form>

<script>

var lokasiaddrs = {};
{% for lokasi in lokasis %}
lokasiaddrs["{{ lokasi.0 }}"] = "{{ lokasi.1 }}";
{% endfor %}

var tipefaskes = {};
{% for tipe_faskes in tipe_faskeses %}
tipefaskes["{{ tipe_faskes.0 }}"] = "{{ tipe_faskes.1 }}";
{% endfor %}

function changelokasiaddress() {
    formtext = document.getElementById("lokasiaddress");
    formtext.value = "";
    formselect = document.getElementById("id_lokasi");
    formval = formselect.value;
    formtext.value = lokasiaddrs[formval];
}

function changetipefaskes() {
    formtext = document.getElementById("tipefaskesname");
    formtext.value = "";
    formselect = document.getElementById("kode_tipe_faskes");
    formval = formselect.value;
    formtext.value = tipefaskes[formval];
}

(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();

</script>

{% endblock body %}

faskes/templates/faskes/index.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == "success" %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

<h2>Fasilitas Kesehatan</h2>

{% if request.session.role == 'admin' %}

<a class="btn btn-primary mb-2" href="{% url 'faskes:addfaskes' %}">Tambah Faskes</a>
<table class="table table-bordered table-hover">
    <tr>
        <th scope="col">Kode Faskes</th>
        <th scope="col">Lokasi</th>
        <th scope="col">Petugas Faskes</th>
        <th scope="col">Tipe Faskes</th>
        <th scope="col">Action</th>
    </tr>

    {% for faskes in faskeses %}

    <tr>
        <td>{{ faskes.0 }}</td>
        <td>{{ faskes.1 }}</td>
        <td>{{ faskes.2 }}</td>
        <td>{{ faskes.3 }}</td>
        <td>
            <a class="btn btn-primary" href="{% url 'faskes:updatefaskes'%}?kode_faskes={{faskes.0}}">Update</a>
            <form method="POST" action="{% url 'faskes:deletefaskes' %}">
                {% csrf_token %}
                <input name="kode_faskes" value="{{faskes.0}}" hidden>
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
        </td>
    </tr>

    {% endfor %}
</table>

{% elif request.session.role == 'supplier' %}

<table class="table table-bordered table-hover">
    <tr>
        <th scope="col">Kode Faskes</th>
        <th scope="col">Lokasi</th>
        <th scope="col">Petugas Faskes</th>
        <th scope="col">Tipe Faskes</th>
    </tr>

    {% for faskes in faskeses %}

    <tr>
        <td>{{ faskes.0 }}</td>
        <td>{{ faskes.1 }}</td>
        <td>{{ faskes.2 }}</td>
        <td>{{ faskes.3 }}</td>
    </tr>

    {% endfor %}
</table>

{% else %}

<p>Role yang bisa mengakses hanya admin dan supplier</p>

{% endif %}

{% endblock body %}

faskes/templates/faskes/updatefaskes.html
{% extends 'pengguna/base.html' %}

{% block body %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == "success" %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-warning" role="alert">
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

<h2>Form Update Fasilitas Kesehatan</h2>

<form method="POST" action="{% url 'faskes:updatefaskes' %}">
    {% csrf_token %}

    <input type="text" name="kode_faskes" value="{{ current.0 }}" hidden>
    
    <div class="form-group">
        <label for="id_lokasi">Id Lokasi:</label>
        <select class="form-control" name="id_lokasi" id="id_lokasi" onchange=changelokasiaddress() required>
            <option value="{{ current.1 }}" selected>{{ current.1 }}</option>
            {% for lokasi in lokasis %}
                {% if lokasi.0 != current.1 %}
                    <option value="{{ lokasi.0 }}">{{ lokasi.0 }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="lokasiaddress">Lokasi</label>
        <input class="form-control" type="text" id="lokasiaddress" disabled>
    </div>

    <div class="form-group">
        <label for="username_petugas">Petugas Faskes:</label>
        <select class="form-control" name="username_petugas" id="username_petugas" required>
            <option value="{{ current.2 }}" selected>{{ current.3 }}</option>
            {% for petugas_faskes in petugas_faskeses %}
                <option value="{{ petugas_faskes.0 }}">{{ petugas_faskes.1 }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="kode_tipe_faskes">Kode Tipe Faskes:</label>
        <select class="form-control" name="kode_tipe_faskes" id="kode_tipe_faskes" onchange=changetipefaskes() required>
            <option value="{{ current.4 }}" selected>{{ current.4 }}</option>
            {% for tipe_faskes in tipe_faskeses %}
                {% if tipe_faskes.0 != current.4 %}
                    <option value="{{ tipe_faskes.0 }}">{{ tipe_faskes.0 }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
        <label for="tipefaskesname">Tipe Faskes:</label>
        <input class="form-control" type="text" id="tipefaskesname" disabled>
    </div>

    <input class="btn btn-primary" type="submit" value="Simpan">
    <a class="btn btn-danger" href="{% url 'faskes:index' %}">batal</a>
</form>

<script>

var lokasiaddrs = {};
{% for lokasi in lokasis %}
lokasiaddrs["{{ lokasi.0 }}"] = "{{ lokasi.1 }}";
{% endfor %}

var tipefaskes = {};
{% for tipe_faskes in tipe_faskeses %}
tipefaskes["{{ tipe_faskes.0 }}"] = "{{ tipe_faskes.1 }}";
{% endfor %}

function changelokasiaddress() {
    formtext = document.getElementById("lokasiaddress");
    formtext.value = "";
    formselect = document.getElementById("id_lokasi");
    formval = formselect.value;
    formtext.value = lokasiaddrs[formval];
}

function changetipefaskes() {
    formtext = document.getElementById("tipefaskesname");
    formtext.value = "";
    formselect = document.getElementById("kode_tipe_faskes");
    formval = formselect.value;
    formtext.value = tipefaskes[formval];
}

document.addEventListener("DOMContentLoaded", function(event) { 
    changelokasiaddress();
    changetipefaskes();
});

</script>

{% endblock body %}